import { act, renderHook } from "@testing-library/react";
import { afterEach, expect, it, vi } from "vitest";
import { useResourceAutosave } from "./useResourceAutosave";
afterEach(() => { vi.useRealTimers(); sessionStorage.clear(); });
it("keeps a failed draft and retries it", async () => {
  const save = vi.fn().mockRejectedValueOnce(new Error("offline")).mockResolvedValue({ notes: "Draft" });
  const { result } = renderHook(() => useResourceAutosave({ resourceKey: "retry", initialValue: { notes: "" }, save }));
  act(() => result.current.update({ notes: "Draft" }));
  await act(async () => result.current.flush());
  expect(result.current.saveState).toBe("failed");
  expect(result.current.draft.notes).toBe("Draft");
  await act(async () => result.current.retry());
  expect(result.current.saveState).toBe("saved");
});
it("does not apply an old save response to the new resource", async () => {
  let resolve;
  const oldSave = () => new Promise(r => { resolve = r; });
  const { result, rerender } = renderHook(({ key }) => useResourceAutosave({ resourceKey: key, initialValue: { notes: key }, save: oldSave }), { initialProps: { key: "a" } });
  act(() => result.current.update({ notes: "Changed A" }));
  act(() => { void result.current.flush(); });
  rerender({ key: "b" });
  await act(async () => resolve({ notes: "Changed A" }));
  expect(result.current.draft.notes).toBe("b");
});
it("restores queued text after navigation without writing into another resource", () => {
  vi.useFakeTimers();
  const save = vi.fn();
  const first = renderHook(() => useResourceAutosave({ resourceKey: "draft", initialValue: { notes: "" }, save }));
  act(() => first.result.current.update({ notes: "Keep this" }));
  first.unmount();
  act(() => vi.advanceTimersByTime(1000));
  expect(save).not.toHaveBeenCalled();
  const next = renderHook(() => useResourceAutosave({ resourceKey: "draft", initialValue: { notes: "" }, save }));
  expect(next.result.current.draft.notes).toBe("Keep this");
});
it("retains in-flight and newer fields together in the recovery draft", async () => {
  let reject;
  const save = vi.fn(() => new Promise((_, r) => { reject = r; }));
  const first = renderHook(() => useResourceAutosave({ resourceKey: "in-flight", initialValue: { title: "Old", content: "" }, save }));
  act(() => first.result.current.update({ title: "New title" }));
  act(() => { void first.result.current.flush(); });
  act(() => first.result.current.update({ content: "New content" }));
  first.unmount();
  const restored = renderHook(() => useResourceAutosave({ resourceKey: "in-flight", initialValue: { title: "Old", content: "" }, save }));
  expect(restored.result.current.draft).toEqual({ title: "New title", content: "New content" });
  restored.unmount();
  await act(async () => reject(new Error("offline")));
});
it("does not erase a newer recovered draft when an old response arrives", async () => {
  let resolve;
  const oldSave = () => new Promise(r => { resolve = r; });
  const first = renderHook(() => useResourceAutosave({ resourceKey: "revisited", initialValue: { notes: "Old" }, save: oldSave }));
  act(() => first.result.current.update({ notes: "First edit" }));
  act(() => { void first.result.current.flush(); });
  first.unmount();
  const next = renderHook(() => useResourceAutosave({ resourceKey: "revisited", initialValue: { notes: "Old" }, save: vi.fn() }));
  act(() => next.result.current.update({ notes: "Latest edit" }));
  await act(async () => resolve({ notes: "First edit" }));
  next.unmount();
  const restored = renderHook(() => useResourceAutosave({ resourceKey: "revisited", initialValue: { notes: "First edit" }, save: vi.fn() }));
  expect(restored.result.current.draft.notes).toBe("Latest edit");
});
it("serializes saves across a resource's remount", async () => {
  let resolve;
  const oldSave = () => new Promise(r => { resolve = r; });
  const first = renderHook(() => useResourceAutosave({ resourceKey: "serialized", initialValue: { notes: "Old" }, save: oldSave }));
  act(() => first.result.current.update({ notes: "First edit" }));
  act(() => { void first.result.current.flush(); });
  first.unmount();
  const newSave = vi.fn().mockResolvedValue({ notes: "Latest edit" });
  const next = renderHook(() => useResourceAutosave({ resourceKey: "serialized", initialValue: { notes: "Old" }, save: newSave }));
  act(() => next.result.current.update({ notes: "Latest edit" }));
  let finishing;
  act(() => { finishing = next.result.current.flush(); });
  expect(newSave).not.toHaveBeenCalled();
  await act(async () => { resolve({ notes: "First edit" }); await finishing; });
  expect(next.result.current.draft.notes).toBe("Latest edit");
});
it("does not replay an inactive editor's queued changes after a newer editor saves", async () => {
  let resolve;
  const oldSave = vi.fn().mockImplementationOnce(() => new Promise(r => { resolve = r; })).mockResolvedValue({ notes: "Older queued edit" });
  const first = renderHook(() => useResourceAutosave({ resourceKey: "inactive", initialValue: { notes: "Old" }, save: oldSave }));
  act(() => first.result.current.update({ notes: "First edit" }));
  let oldFlush;
  act(() => { oldFlush = first.result.current.flush(); });
  act(() => first.result.current.update({ notes: "Older queued edit" }));
  first.unmount();
  const newSave = vi.fn().mockResolvedValue({ notes: "Newest edit" });
  const next = renderHook(() => useResourceAutosave({ resourceKey: "inactive", initialValue: { notes: "Old" }, save: newSave }));
  act(() => next.result.current.update({ notes: "Newest edit" }));
  let newFlush;
  act(() => { newFlush = next.result.current.flush(); });
  await act(async () => { resolve({ notes: "First edit" }); await Promise.all([oldFlush, newFlush]); });
  expect(oldSave).toHaveBeenCalledTimes(1);
  expect(newSave).toHaveBeenCalledWith({ notes: "Newest edit" });
});
