"""initial schema

Revision ID: 20260928_0001
Revises:
Create Date: 2026-09-28 00:54:45.475042
"""

from typing import Sequence, Union
from datetime import datetime, timezone

from alembic import op
import sqlalchemy as sa

revision: str = "20260928_0001"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_settings",
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "plans",
        sa.Column("plan_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("price_cents", sa.Integer(), nullable=False),
        sa.Column("credits", sa.Integer(), nullable=False),
        sa.Column("features", sa.JSON(), nullable=False),
        sa.Column("stripe_price_id", sa.String(length=255), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("plan_id"),
        sa.UniqueConstraint("stripe_price_id"),
    )
    op.create_table(
        "stripe_events",
        sa.Column("event_id", sa.String(length=255), nullable=False),
        sa.Column("event_type", sa.String(length=160), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("stripe_created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_index(
        op.f("ix_stripe_events_stripe_created_at"),
        "stripe_events",
        ["stripe_created_at"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("normalized_email", sa.String(length=320), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("google_sub", sa.String(length=255), nullable=True),
        sa.Column("picture", sa.String(length=1024), nullable=True),
        sa.Column("auth_provider", sa.String(length=32), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("plan_id", sa.String(length=64), nullable=False),
        sa.Column("stripe_customer_id", sa.String(length=255), nullable=True),
        sa.Column("stripe_subscription_id", sa.String(length=255), nullable=True),
        sa.Column("subscription_status", sa.String(length=64), nullable=True),
        sa.Column("onboarded", sa.Boolean(), nullable=False),
        sa.Column("theme", sa.String(length=16), nullable=False),
        sa.Column("timezone_offset_min", sa.Integer(), nullable=False),
        sa.Column("daily_goal_minutes", sa.Integer(), nullable=False),
        sa.Column("ai_credits_remaining", sa.Integer(), nullable=False),
        sa.Column("credit_period", sa.String(length=7), nullable=True),
        sa.Column("credit_bonuses", sa.JSON(), nullable=False),
        sa.Column("referral_code", sa.String(length=24), nullable=True),
        sa.Column("referred_by", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["plans.plan_id"],
        ),
        sa.ForeignKeyConstraint(["referred_by"], ["users.user_id"]),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("google_sub"),
        sa.UniqueConstraint("normalized_email"),
        sa.UniqueConstraint("referral_code"),
        sa.UniqueConstraint("stripe_customer_id"),
        sa.UniqueConstraint("stripe_subscription_id"),
    )
    op.create_index(op.f("ix_users_plan_id"), "users", ["plan_id"], unique=False)
    op.create_table(
        "ai_usage_logs",
        sa.Column("usage_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("feature", sa.String(length=64), nullable=False),
        sa.Column("ok", sa.Boolean(), nullable=False),
        sa.Column("credits", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("usage_id"),
    )
    op.create_index(
        "ix_ai_usage_owner_at", "ai_usage_logs", ["user_id", "created_at"], unique=False
    )
    op.create_table(
        "oauth_login_codes",
        sa.Column("code_id", sa.String(length=36), nullable=False),
        sa.Column("code_hash", sa.String(length=128), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("client_kind", sa.String(length=16), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("code_id"),
        sa.UniqueConstraint("code_hash"),
    )
    op.create_index(
        "ix_oauth_login_codes_expires_used",
        "oauth_login_codes",
        ["expires_at", "used_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_oauth_login_codes_user_id"),
        "oauth_login_codes",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "payment_transactions",
        sa.Column("transaction_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("plan_id", sa.String(length=64), nullable=True),
        sa.Column("stripe_checkout_session_id", sa.String(length=255), nullable=False),
        sa.Column("stripe_customer_id", sa.String(length=255), nullable=True),
        sa.Column("stripe_subscription_id", sa.String(length=255), nullable=True),
        sa.Column("last_stripe_event_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("payment_status", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["plan_id"], ["plans.plan_id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("transaction_id"),
        sa.UniqueConstraint("stripe_checkout_session_id"),
    )
    op.create_index(
        op.f("ix_payment_transactions_stripe_customer_id"),
        "payment_transactions",
        ["stripe_customer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payment_transactions_stripe_subscription_id"),
        "payment_transactions",
        ["stripe_subscription_id"],
        unique=False,
    )
    op.create_index(
        "ix_payment_transactions_user_created",
        "payment_transactions",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "referrals",
        sa.Column("referral_id", sa.String(length=36), nullable=False),
        sa.Column("referrer_id", sa.String(length=36), nullable=False),
        sa.Column("referred_user_id", sa.String(length=36), nullable=False),
        sa.Column("credits_awarded", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["referred_user_id"],
            ["users.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["referrer_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("referral_id"),
    )
    op.create_index("ix_referrals_referrer", "referrals", ["referrer_id"], unique=False)
    op.create_index(
        "uq_referrals_referred", "referrals", ["referred_user_id"], unique=True
    )
    op.create_table(
        "streaks",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("current", sa.Integer(), nullable=False),
        sa.Column("longest", sa.Integer(), nullable=False),
        sa.Column("last_day", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "subjects",
        sa.Column("subject_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("color", sa.String(length=32), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("focus_minutes", sa.Integer(), nullable=False),
        sa.Column("break_minutes", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("subject_id"),
    )
    op.create_index(
        "ix_subjects_owner_created", "subjects", ["user_id", "created_at"], unique=False
    )
    op.create_table(
        "timetable_entries",
        sa.Column("timetable_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("subject_id", sa.String(length=36), nullable=True),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("day_of_week", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.String(length=8), nullable=False),
        sa.Column("end_time", sa.String(length=8), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("recurrence", sa.String(length=24), nullable=False),
        sa.Column("location", sa.String(length=240), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["subject_id"], ["subjects.subject_id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("timetable_id"),
    )
    op.create_index(
        "ix_timetable_owner_day_time",
        "timetable_entries",
        ["user_id", "day_of_week", "start_time"],
        unique=False,
    )
    op.create_table(
        "units",
        sa.Column("unit_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("subject_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["subject_id"], ["subjects.subject_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("unit_id"),
    )
    op.create_index(
        "ix_units_owner_subject_order",
        "units",
        ["user_id", "subject_id", "position"],
        unique=False,
    )
    op.create_table(
        "lessons",
        sa.Column("lesson_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("subject_id", sa.String(length=36), nullable=False),
        sa.Column("unit_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("total_seconds", sa.Integer(), nullable=False),
        sa.Column("last_studied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subjects.subject_id"],
        ),
        sa.ForeignKeyConstraint(["unit_id"], ["units.unit_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("lesson_id"),
    )
    op.create_index(
        "ix_lessons_owner_unit_order",
        "lessons",
        ["user_id", "unit_id", "position"],
        unique=False,
    )
    op.create_table(
        "notebooks",
        sa.Column("notebook_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("subject_id", sa.String(length=36), nullable=True),
        sa.Column("lesson_id", sa.String(length=36), nullable=True),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["lesson_id"], ["lessons.lesson_id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"], ["subjects.subject_id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("notebook_id"),
    )
    op.create_index(
        op.f("ix_notebooks_lesson_id"), "notebooks", ["lesson_id"], unique=False
    )
    op.create_index(
        op.f("ix_notebooks_subject_id"), "notebooks", ["subject_id"], unique=False
    )
    op.create_index(
        "ix_notebooks_owner_updated",
        "notebooks",
        ["user_id", "updated_at"],
        unique=False,
    )
    op.create_table(
        "reviews",
        sa.Column("review_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("lesson_id", sa.String(length=36), nullable=True),
        sa.Column("next_review_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("interval_days", sa.Integer(), nullable=False),
        sa.Column("step_index", sa.Integer(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["lesson_id"], ["lessons.lesson_id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("review_id"),
    )
    op.create_index(
        "ix_reviews_owner_due", "reviews", ["user_id", "next_review_at"], unique=False
    )
    op.create_index(
        "ix_reviews_owner_lesson", "reviews", ["user_id", "lesson_id"], unique=True
    )
    op.create_table(
        "study_sessions",
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("subject_id", sa.String(length=36), nullable=True),
        sa.Column("unit_id", sa.String(length=36), nullable=True),
        sa.Column("lesson_id", sa.String(length=36), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=False),
        sa.Column("mode", sa.String(length=32), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["lesson_id"], ["lessons.lesson_id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"], ["subjects.subject_id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["unit_id"], ["units.unit_id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("session_id"),
    )
    op.create_index(
        "ix_study_sessions_owner_started",
        "study_sessions",
        ["user_id", "started_at"],
        unique=False,
    )
    op.create_table(
        "tasks",
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("subject_id", sa.String(length=36), nullable=True),
        sa.Column("unit_id", sa.String(length=36), nullable=True),
        sa.Column("lesson_id", sa.String(length=36), nullable=True),
        sa.Column("title", sa.String(length=320), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("due_time", sa.String(length=8), nullable=True),
        sa.Column("priority", sa.String(length=16), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("reminder_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed", sa.Boolean(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["lesson_id"], ["lessons.lesson_id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"], ["subjects.subject_id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["unit_id"], ["units.unit_id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("task_id"),
    )
    op.create_index(
        "ix_tasks_owner_due",
        "tasks",
        ["user_id", "due_date", "completed"],
        unique=False,
    )
    now = datetime.now(timezone.utc)
    plans = sa.table(
        "plans",
        sa.column("plan_id", sa.String),
        sa.column("name", sa.String),
        sa.column("price_cents", sa.Integer),
        sa.column("credits", sa.Integer),
        sa.column("features", sa.JSON),
        sa.column("stripe_price_id", sa.String),
        sa.column("active", sa.Boolean),
        sa.column("created_at", sa.DateTime(timezone=True)),
        sa.column("updated_at", sa.DateTime(timezone=True)),
    )
    op.bulk_insert(
        plans,
        [
            {
                "plan_id": "freshman",
                "name": "Freshman",
                "price_cents": 0,
                "credits": 10,
                "features": ["All study tools", "Study progress"],
                "stripe_price_id": None,
                "active": True,
                "created_at": now,
                "updated_at": now,
            },
            {
                "plan_id": "scholar",
                "name": "Scholar",
                "price_cents": 799,
                "credits": 500,
                "features": ["500 study companion helps", "All study tools"],
                "stripe_price_id": None,
                "active": True,
                "created_at": now,
                "updated_at": now,
            },
            {
                "plan_id": "deans_list",
                "name": "Dean's List",
                "price_cents": 1499,
                "credits": 3000,
                "features": ["3000 study companion helps", "All study tools"],
                "stripe_price_id": None,
                "active": True,
                "created_at": now,
                "updated_at": now,
            },
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_tasks_owner_due", table_name="tasks")
    op.drop_table("tasks")
    op.drop_index("ix_study_sessions_owner_started", table_name="study_sessions")
    op.drop_table("study_sessions")
    op.drop_index("ix_reviews_owner_lesson", table_name="reviews")
    op.drop_index("ix_reviews_owner_due", table_name="reviews")
    op.drop_table("reviews")
    op.drop_index("ix_notebooks_owner_updated", table_name="notebooks")
    op.drop_index(op.f("ix_notebooks_subject_id"), table_name="notebooks")
    op.drop_index(op.f("ix_notebooks_lesson_id"), table_name="notebooks")
    op.drop_table("notebooks")
    op.drop_index("ix_lessons_owner_unit_order", table_name="lessons")
    op.drop_table("lessons")
    op.drop_index("ix_units_owner_subject_order", table_name="units")
    op.drop_table("units")
    op.drop_index("ix_timetable_owner_day_time", table_name="timetable_entries")
    op.drop_table("timetable_entries")
    op.drop_index("ix_subjects_owner_created", table_name="subjects")
    op.drop_table("subjects")
    op.drop_table("streaks")
    op.drop_index("uq_referrals_referred", table_name="referrals")
    op.drop_index("ix_referrals_referrer", table_name="referrals")
    op.drop_table("referrals")
    op.drop_index(
        "ix_payment_transactions_user_created", table_name="payment_transactions"
    )
    op.drop_index(
        op.f("ix_payment_transactions_stripe_customer_id"),
        table_name="payment_transactions",
    )
    op.drop_index(
        op.f("ix_payment_transactions_stripe_subscription_id"),
        table_name="payment_transactions",
    )
    op.drop_table("payment_transactions")
    op.drop_index(op.f("ix_oauth_login_codes_user_id"), table_name="oauth_login_codes")
    op.drop_index("ix_oauth_login_codes_expires_used", table_name="oauth_login_codes")
    op.drop_table("oauth_login_codes")
    op.drop_index("ix_ai_usage_owner_at", table_name="ai_usage_logs")
    op.drop_table("ai_usage_logs")
    op.drop_index(op.f("ix_users_plan_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(
        op.f("ix_stripe_events_stripe_created_at"), table_name="stripe_events"
    )
    op.drop_table("stripe_events")
    op.drop_table("plans")
    op.drop_table("app_settings")
    # ### end Alembic commands ###
