import React from "react";
import LegalLayout, { LegalSection } from "@/components/LegalLayout";

export default function Terms() {
  return (
    <LegalLayout
      title="Terms of Service"
      summary="These terms describe the rules for using Syllo, including accounts, Study Companion helps, subscriptions, student content, and responsible academic use."
    >
      <LegalSection title="Agreement and operator">
        <p>These Terms form an agreement between you and <strong>Kavindra Senanayake, an individual trading as Syllo (Kavin HQ)</strong>, based in Colombo, Sri Lanka. By creating an account, using Google sign-in, or otherwise using Syllo, you agree to these Terms and the Privacy Policy.</p>
      </LegalSection>

      <LegalSection title="Students and guardian permission">
        <p>Syllo is intended for students of different ages. If you are under 16, you may use Syllo only with permission from a parent or legal guardian. By creating an account, you confirm that you have this permission. A parent or guardian who permits use is responsible for supervising the child’s account and use of the service.</p>
      </LegalSection>

      <LegalSection title="Your account">
        <p>Provide accurate information, keep your credentials secure, and tell us promptly if you believe your account has been compromised. You are responsible for activity performed through your account. Do not sell, transfer, or share access in a way that undermines account security or plan limits.</p>
      </LegalSection>

      <LegalSection title="Educational service and Study Companion">
        <p>Syllo helps organize study activity; it is not a school, tutor, examination authority, or provider of professional advice. Study Companion responses are generated by Google Gemini and may be incomplete or incorrect. Verify important answers against teachers, course materials, or reliable sources.</p>
        <p>Use Syllo consistently with your school’s academic-integrity rules. You remain responsible for work you submit and decisions you make based on information in Syllo.</p>
      </LegalSection>

      <LegalSection title="Plans, helps, and referrals">
        <p>Plans may include a monthly allowance of Study Companion “helps”. One usable successful response consumes one help; failed or empty responses are not intended to consume a help. Allowances, milestone bonuses, and referral rewards have no cash value, may not be transferred, and may be limited or withdrawn where we detect abuse, duplicate accounts, automation, or fraud.</p>
        <p>We may adjust future plan allowances or promotional rewards. Changes will not retroactively alter a paid billing period except where required to prevent abuse or comply with law.</p>
      </LegalSection>

      <LegalSection title="Subscriptions and payment">
        <p>Paid plans are not currently available. Scholar and Dean’s List are shown as upcoming plans, and displaying a planned price is not an offer to take payment.</p>
        <p>When paid subscriptions launch, the checkout will show the payment provider, recurring price, billing interval, taxes, introductory terms, cancellation process, and any applicable refund terms before purchase.</p>
      </LegalSection>

      <LegalSection title="Your content">
        <p>You retain ownership of notes, tasks, lesson content, and other material you add. You give Syllo a limited permission to host, process, back up, display, and transmit that content only as needed to provide and secure the service. You are responsible for having the right to upload your content.</p>
      </LegalSection>

      <LegalSection title="Acceptable use">
        <p>Do not use Syllo to break the law, infringe rights, distribute malware, harass others, probe or bypass security, scrape the service, overload infrastructure, create accounts or referrals fraudulently, evade plan limits, or use automated access without written permission.</p>
      </LegalSection>

      <LegalSection title="Syllo ownership">
        <p>Syllo’s software, interface, branding, and original materials belong to Kavindra Senanayake, trading as Syllo (Kavin HQ), or its licensors. These Terms give you a personal, limited, revocable, non-exclusive right to use the service; they do not transfer ownership of Syllo.</p>
      </LegalSection>

      <LegalSection title="Availability, suspension, and changes">
        <p>We work to keep Syllo available but do not promise uninterrupted or error-free operation. We may change, pause, or discontinue features; suspend accounts that threaten the service or violate these Terms; and terminate accounts where reasonably necessary. You may stop using Syllo at any time and may request account deletion.</p>
      </LegalSection>

      <LegalSection title="Disclaimers and liability">
        <p>To the extent permitted by law, Syllo is provided “as is” and “as available”. We disclaim implied warranties that cannot reasonably apply to a changing online study service. To the extent permitted by law, Kavindra Senanayake, trading as Syllo (Kavin HQ), is not liable for indirect, incidental, special, or consequential losses, lost study data, missed deadlines, academic outcomes, or reliance on generated content. Nothing in these Terms excludes rights or liability that cannot legally be excluded.</p>
      </LegalSection>

      <LegalSection title="Governing law and contact">
        <p>These Terms are governed by the laws of Sri Lanka. Disputes are subject to the jurisdiction of the competent courts of Sri Lanka, without limiting any mandatory consumer rights that apply to you.</p>
        <p>Questions about these Terms may be sent to <a href="mailto:support@syllo.kavinhq.com">support@syllo.kavinhq.com</a>. Privacy requests may be sent to <a href="mailto:privacy@syllo.kavinhq.com">privacy@syllo.kavinhq.com</a>.</p>
      </LegalSection>
    </LegalLayout>
  );
}
